services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: us-east4-docker.pkg.dev/mimetic-encoder-419710/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports: 
      - '3004:3004'
  auth:
    image: us-east4-docker.pkg.dev/mimetic-encoder-419710/auth/production
    env_file:
      - ../apps/auth/.env
    ports: 
      - '3003:3003'
  payments:
    image: us-east4-docker.pkg.dev/mimetic-encoder-419710/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3001:3001'
  notifications:
    image: us-east4-docker.pkg.dev/mimetic-encoder-419710/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports: 
      - '3000:3000'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    
  
  
